aws:
  region_name: us-west-2
  model_id: anthropic.claude-3-sonnet-20240229-v1:0
  prompts:
    full: Extract data from attached invoice in key-value format.
    structured: |
        Process the pdf invoice and list all metadata and values in json format for the variables with descriptions in <variables></variables> tags. The result should be returned as JSON as given in the <output></output> tags.

        <variables>
        Vendor: Name of the company or entity the invoice is from.
        InvoiceDate: Date the invoice was created.
        DueDate: Date the invoice is due and needs to be paid by.
        CurrencyCode: Currency code for the invoice amount based on the symbol and vendor details.
        TotalAmountDue: Total amount dur for the invoice
        Description: a concise summary of the invoice description within 20 words
        </variables>

        Format your analysis as a JSON object in following structure:
        <output>
        {
        "Vendor": "<vendor name>",
        "InvoiceDate":"<DD-MM-YYYY>",
        "DueDate":"<DD-MM-YYYY>",
        "CurrencyCode":"<Currency code based on the symbol and vendor details>",
        "TotalAmountDue":"<100.90>" # should be a decimal number in string
        "Description":"<Concise summary of the invoice description within 20 words>"
        }
        </output>
        Please proceed with the analysis based on the above instructions. Please don't state "Based on the .."
    summary: Process the pdf invoice and summarize the invoice under 3 lines

processing:
  output_file: processed_invoice_output.json
  local_download_folder: invoices
